# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: yarn build
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: yarn test

orbs:
  node: circleci/node@4.7

workflows:
  test-workflow:
    jobs:
      - build:
          pkg-manager: yarn
      - test:
          requires:
            - build
          pkg-manager: yarn

